# Site settings
title: "Anna's resume"
description: "My resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Anna Westin"
resume_title:                   "Intelligent Automation Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "anna.westin42@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "xxx-xxx"
resume_contact_address:         "Edinburgh"

resume_header_contact_info:     "Edinburgh • xxx-xxx • "
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a Swedish automation engineer who has been residing in Edinburgh since the end of 2020. <br><br> I have realized that my most fulfilling work experiences happen when I am part of a diverse team that utilizes our differences to our advantage, resulting in seamless teamwork. I enjoy collaborating with others and contributing to the team's achievements and camaraderie. <br><br>In my leisure time, you’ll either find me gaming, freediving or studying to further expand my knowledge of different topics. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/annawestin?tab=repositories"
#  resume_twitter_url:           "http://twitter.com/jglovier"
# resume_dribbble_url:          "https://dribbble.com/jag"
# resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/anna-westin-593626173"
  resume_instagram_url:         "https://www.instagram.com/jekyllompa"
#  resume_website_url:           "http://joelglovier.com"
#  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
